import Foundation
import CryptoKit

struct VerifiedLicense {
    let version: Int
    let product: String
    let licenseID: String
    let fullName: String
    let username: String
    let issuedAt: String
}

enum LicenseVerificationError: LocalizedError {
    case malformedFormat
    case invalidBase64
    case invalidPayload
    case invalidSignature
    case unsupportedVersion
    case unsupportedProduct
    case missingField(String)

    var errorDescription: String? {
        switch self {
        case .malformedFormat:
            return "Invalid license format."
        case .invalidBase64:
            return "Invalid license encoding."
        case .invalidPayload:
            return "Invalid license payload."
        case .invalidSignature:
            return "License signature is invalid."
        case .unsupportedVersion:
            return "This license version is not supported."
        case .unsupportedProduct:
            return "This license is not for SensorSync Recorder."
        case .missingField(let field):
            return "License is missing \(field)."
        }
    }
}

enum LicenseVerifier {
    private static let prefix = "SSLR1"
    private static let product = "iPhoneSensorRecorder"

    // Development public key only.
    // This is the PEM public key generated by the Windows license generator.
    private static let publicKeyPEM = """
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEANN9rU/PH/4/6wD0Hp5MFL0tOqD0otYJg5Tpl79XJHPc=
    -----END PUBLIC KEY-----
    """

    static func verify(
        licenseKey: String,
        fullName: String,
        username: String
    ) throws -> VerifiedLicense {
        let enteredName = fullName.trimmingCharacters(in: .whitespacesAndNewlines)
        let enteredUsername = username.trimmingCharacters(in: .whitespacesAndNewlines)
        let key = licenseKey.trimmingCharacters(in: .whitespacesAndNewlines)

        guard !enteredName.isEmpty else {
            throw LicenseVerificationError.missingField("Full Name")
        }
        guard !enteredUsername.isEmpty else {
            throw LicenseVerificationError.missingField("Username")
        }
        guard !key.isEmpty else {
            throw LicenseVerificationError.missingField("License Key")
        }

        let parts = key.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 3, parts[0] == prefix else {
            throw LicenseVerificationError.malformedFormat
        }

        let payloadBytes = try decodeBase64URL(String(parts[1]))
        let signatureBytes = try decodeBase64URL(String(parts[2]))

        guard signatureBytes.count == 64 else {
            throw LicenseVerificationError.invalidSignature
        }

        guard
            let jsonObject = try? JSONSerialization.jsonObject(with: payloadBytes),
            let payload = jsonObject as? [String: Any]
        else {
            throw LicenseVerificationError.invalidPayload
        }

        // The Windows generator signs the exact canonical JSON bytes:
        // sorted keys, no whitespace, UTF-8, Unicode preserved.
        let canonicalBytes = try canonicalPayload(payload)

        let publicKey = try makePublicKey()
        guard publicKey.isValidSignature(signatureBytes, for: canonicalBytes) else {
            throw LicenseVerificationError.invalidSignature
        }

        guard let version = payload["version"] as? Int else {
            throw LicenseVerificationError.missingField("version")
        }
        guard let product = payload["product"] as? String else {
            throw LicenseVerificationError.missingField("product")
        }
        guard let licenseID = payload["license_id"] as? String, !licenseID.isEmpty else {
            throw LicenseVerificationError.missingField("license_id")
        }
        guard let payloadName = payload["full_name"] as? String else {
            throw LicenseVerificationError.missingField("full_name")
        }
        guard let payloadUsername = payload["username"] as? String else {
            throw LicenseVerificationError.missingField("username")
        }
        guard let issuedAt = payload["issued_at"] as? String else {
            throw LicenseVerificationError.missingField("issued_at")
        }

        guard version == 1 else {
            throw LicenseVerificationError.unsupportedVersion
        }
        guard product == Self.product else {
            throw LicenseVerificationError.unsupportedProduct
        }
        guard payloadName == enteredName else {
            throw LicenseVerificationError.invalidPayload
        }
        guard payloadUsername == enteredUsername else {
            throw LicenseVerificationError.invalidPayload
        }

        return VerifiedLicense(
            version: version,
            product: product,
            licenseID: licenseID,
            fullName: payloadName,
            username: payloadUsername,
            issuedAt: issuedAt
        )
    }

    private static func makePublicKey() throws -> Curve25519.Signing.PublicKey {
        let lines = publicKeyPEM
            .components(separatedBy: .newlines)
            .filter {
                !$0.contains("BEGIN PUBLIC KEY") &&
                !$0.contains("END PUBLIC KEY") &&
                !$0.isEmpty
            }

        guard let der = Data(base64Encoded: lines.joined()) else {
            throw LicenseVerificationError.invalidBase64
        }

        // SubjectPublicKeyInfo for Ed25519 is 44 bytes:
        // 12-byte DER prefix + 32-byte raw public key.
        guard der.count == 44 else {
            throw LicenseVerificationError.invalidPayload
        }

        let rawKey = der.suffix(32)
        return try Curve25519.Signing.PublicKey(rawRepresentation: rawKey)
    }

    private static func decodeBase64URL(_ value: String) throws -> Data {
        guard !value.contains("=") else {
            throw LicenseVerificationError.invalidBase64
        }

        var base64 = value
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")

        base64 += String(repeating: "=", count: (4 - base64.count % 4) % 4)

        guard let data = Data(base64Encoded: base64) else {
            throw LicenseVerificationError.invalidBase64
        }

        return data
    }

    private static func canonicalPayload(_ payload: [String: Any]) throws -> Data {
        // JSONSerialization with .sortedKeys matches Python:
        // json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        guard JSONSerialization.isValidJSONObject(payload) else {
            throw LicenseVerificationError.invalidPayload
        }

        return try JSONSerialization.data(
            withJSONObject: payload,
            options: [.sortedKeys, .withoutEscapingSlashes]
        )
    }
}
